ldap:
  server: "ldaps://10.0.0.1:636"
  insecure_skip_verify: true

smb:
  server: "10.0.0.1:445"
  username: "global-admin"
  password: "Muster!"
  domain: "LINUXMUSTER"

http:
  address: ":8443"
  webdav_prefix: "/webdav/"
  cert_file: "webdav.pem"
  key_file: "webdav.key"

log:
  level: "error"        # options: trace, debug, info, warn, error, fatal, panic
  file: "./webdav-server.log"